name: HFEX-ICON CI
on:
  #监听push操作
  push:
    branches:
      - master # 这里只配置了main分支，所以只有推送main分支才会触发以下任务
      
  pull_request:
    branches:
      - master
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - name: Checkout  ️ 
        uses: actions/checkout@v3

      - name: Install and Build   # 安装依赖、打包，如果提前已打包好无需这一步
        run: |
          npm install
          git config --global user.name 'UzumakiHan'
          git config --global user.email '1750263786@qq.com'
          npm run release
          npm run gitpush
          
